import Head from "next/head";
import { InferGetStaticPropsType } from "next";

import sanityClient from "@lib/sanity";
import Hero from "@feature/hero/Hero";
import About from "@feature/about/About";
import Experience from "@feature/experience/Experience";

export const getStaticProps = async () => {
  const information = await sanityClient.fetch(`*[_type == 'information'][0]`);
  const education = await sanityClient.fetch(`*[_type == 'education']`);
  const work = await sanityClient.fetch(`*[_type == 'experience']`);

  const aboutMe: string = await information.aboutMe;

  return {
    props: {
      aboutMe,
      education,
      work,
    },
  };
};

export default function Home({
  aboutMe,
  education,
  work,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>John Carlo N. Camara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About data={aboutMe} />
      <Experience educExperienceItems={education} workExperienceItems={work} />
    </>
  );
}
